version: '3.1'

services:
  app:
    build: .
    depends_on:
      - mongodb
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - LIVESTREAM_ID=${LIVESTREAM_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - './data:/data'
    networks:
      - mongo-compose-network

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - './data:/data/db'
    networks:
      - mongo-compose-network

networks:
    mongo-compose-network:
      driver: bridge
