version: '3.1'

services:
  app:
    build: .
    depends_on:
      - mongodb
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - LIVESTREAM_ID=${LIVESTREAM_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MONGO_URI=${MONGO_URI}
    networks:
      - mongo-compose-network

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - './data:/data/db'
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
