[tool.poetry]
name = "youtube_chat"
version = "0.1.0"
description = ""
authors = ["dunossauro <mendesxeduardo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.75.1"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
aiofiles = "^0.8.0"
Jinja2 = "^3.1.1"
httpx = "^0.22.0"
python-dotenv = "^0.20.0"
loguru = "^0.6.0"
motor = "^3.0.0"

[tool.poetry.dev-dependencies]
blue = "^0.8.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
xenon = "^0.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
